\documentclass{article}
\usepackage[letterpaper, portrait, margin=1in]{geometry}
\usepackage{amsmath}

\begin{document}
\section*{Final Project Description - Kevin McGregor}
For the final project I plan to address the zero-inflation problem in Tweedie's compound Poisson model. One possible approach is to model the dispersion parameter $\phi$.  The more novel approach is to form a zero-inflated model, which is comprised of a mixture of the Tweedie model, and a point mass at 0.  From this formulation it is possible to model both the mean and the mixture probability.  Parameter estimates can be obtained through the EM algorithm, where sparsity is encouraged by including the LASSO penalty term.  In the project, I will use and extend existing code to implement an R package, and do a comprehensive study on real and simulated data to examine performance.

\end{document}